lib/hidria_web/router.ex
defmodule HidriaWeb.Router do
  use HidriaWeb, :router

  alias HidriaWeb.Plugs.AssignSession
  alias HidriaWeb.Plugs.AuthUser
  alias HidriaWeb.Plugs.AuthEnsure
  alias HidriaWeb.Plugs.AuthRole
  alias HidriaWeb.Plugs.CheckState

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(AssignSession, [:current_station, :current_part])
    plug(AuthUser)
  end

  pipeline :authorize do
    plug(AuthEnsure)
  end

  pipeline :state do
    plug(CheckState, :station)
    plug(CheckState, :part)
  end

  pipeline :operator do
    plug(AuthEnsure)
    plug(AuthRole, :operator)
  end

  pipeline :lead do
    plug(AuthEnsure)
    plug(AuthRole, :lead)
  end

  pipeline :admin do
    plug(AuthEnsure)
    plug(AuthRole, :admin)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", HidriaWeb do
    pipe_through(:browser)
    get("/login", LoginController, :new)
    post("/login", LoginController, :create)
  end

  scope "/", HidriaWeb do
    pipe_through([:browser, :operator])
    resources("/state", StateController, only: [:show, :create, :delete], param: "resource")
    get("/logout", LoginController, :delete)

    resources("/user", UserController, only: [:show, :edit, :update])
    get("/users/:id/newpassword", UserController, :new_password)
    put("/users/:id/updatepassword", UserController, :update_password)

    get("/attachments", Defsol.AttachmentController, :index)
    delete("/attachments/:id", Defsol.AttachmentController, :delete)
  end

  scope "/", HidriaWeb do
    pipe_through([:browser, :operator, :state])

    get("/", HomeController, :index)
  end

  scope "/", HidriaWeb.Shopfloor, as: :shopfloor do
  end

  scope "/", HidriaWeb.Defsol, as: :defsol do
    pipe_through([:browser, :operator, :state])
    resources("/errors", ErrorController, except: [:show, :delete])
    resources("/causes", CauseController, only: [:index, :show, :update])
    resources("/solutions", SolutionController, only: [:index, :show])
    resources("/reports", ReportController, except: [:show])
    resources("/notes", NoteController, except: [:show])
  end

  scope "/admin", HidriaWeb.Admin, as: :admin do
    pipe_through([:browser, :lead])

    resources("/parts", PartController, except: [:show])
    resources("/errors", ErrorController, except: [:show])
    post("/errors/:id/clone", ErrorController, :clone)
    resources("/causes", CauseController, except: [:show])
    resources("/solutions", SolutionController, except: [:show])
    resources("/reports", ReportController)
    resources("/notes", NoteController)
  end

  scope "/admin", HidriaWeb.Admin, as: :admin do
    pipe_through([:browser, :admin])

    resources("/users", UserController)
    resources("/stations", StationController, except: [:show])
    get("/users/:id/newpassword", UserController, :new_password)
    put("/users/:id/updatepassword", UserController, :update_password)
  end

  # Other scopes may use custom stacks.
  scope "/api", HidriaWeb do
    pipe_through(:api)
    post("/attachments", Defsol.AttachmentController, :create)
  end
end

lib/hidria_web/controllers/admin/cause_controller.ex
defmodule HidriaWeb.Admin.CauseController do
  use HidriaWeb, :controller

  alias Hidria.Defsol
  alias Hidria.Defsol.Cause

  def index(conn, params) do
    causes = Defsol.list_causes(params)
    search = get_in(params, ["search"])
    render(conn, "index.html", page: causes, search: search)
  end

  def new(conn, params) do
    changeset = Defsol.change_cause(%Cause{}, params)
    errors = Defsol.list_errors()
    render(conn, "new.html", changeset: changeset, errors: errors)
  end

  def create(conn, params = %{"cause" => cause_params}) do
    attrs = merge_inserted_by(conn, cause_params)

    case Defsol.create_cause(attrs) do
      {:ok, cause} ->
        conn
        |> put_flash(:info, "Cause created successfully.")
        |> redirect(to: redirect_path(conn, cause, params))

      {:error, %Ecto.Changeset{} = changeset} ->
        errors = Defsol.list_errors()
        render(conn, "new.html", changeset: changeset, errors: errors)
    end
  end

  def redirect_path(conn, cause, %{"action" => "attachments"}) do
    admin_cause_path(conn, :edit, cause)
  end

  def redirect_path(conn, cause, %{"action" => "solution"}) do
    admin_solution_path(conn, :new, cause_id: cause.id)
  end

  def redirect_path(conn, _, _), do: admin_cause_path(conn, :index)

  def edit(conn, %{"id" => id}) do
    cause = Defsol.get_cause!(id)
    changeset = Defsol.change_cause(cause)
    errors = Defsol.list_errors()
    render(conn, "edit.html", cause: cause, changeset: changeset, errors: errors)
  end

  def update(conn, params = %{"id" => id, "cause" => cause_params}) do
    cause = Defsol.get_cause!(id)
    attrs = merge_updated_by(conn, cause_params)

    case Defsol.update_cause(cause, attrs) do
      {:ok, cause} ->
        conn
        |> put_flash(:info, "Cause updated successfully.")
        |> redirect(to: redirect_path(conn, cause, params))

      {:error, %Ecto.Changeset{} = changeset} ->
        errors = Defsol.list_errors()
        render(conn, "edit.html", cause: cause, changeset: changeset, errors: errors)
    end
  end

  def delete(conn, %{"id" => id}) do
    cause = Defsol.get_cause!(id)
    {:ok, _cause} = Defsol.delete_cause(cause)

    conn
    |> put_flash(:info, "Cause deleted successfully.")
    |> redirect(to: admin_cause_path(conn, :index))
  end
end

lib/hidria_web/controllers/defsol/attachment_controller.ex
defmodule HidriaWeb.Defsol.AttachmentController do
  use HidriaWeb, :controller

  alias Hidria.Defsol

  def index(conn, params = %{"error_id" => assoc_id}) do
    attachments = Defsol.list_attachments(params)
    finish_path = Map.get(params, "finish_path", admin_error_path(conn, :index))
    render_index(conn, attachments, "error", assoc_id, finish_path)
  end

  def index(conn, params = %{"cause_id" => assoc_id}) do
    attachments = Defsol.list_attachments(params)
    finish_path = Map.get(params, "finish_path", admin_cause_path(conn, :index))
    render_index(conn, attachments, "cause", assoc_id, finish_path)
  end

  def index(conn, params = %{"solution_step_id" => assoc_id}) do
    attachments = Defsol.list_attachments(params)
    finish_path = Map.get(params, "finish_path", admin_solution_path(conn, :index))
    render_index(conn, attachments, "solution-step", assoc_id, finish_path)
  end

  def render_index(conn, attachments, assoc, assoc_id, finish_path) do
    render(
      conn,
      "index.html",
      attachments: attachments,
      assoc_id: assoc_id,
      assoc: assoc,
      delete: true,
      finish_path: finish_path
    )
  end

  def create(conn, params) do
    case Defsol.create_attachment(params) do
      {:ok, attachment} ->
        conn
        |> put_status(:ok)
        |> render("show.json", attachment: attachment)

      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(HidriaWeb.ChangesetView, "error.json", changeset: changeset)
    end
  end

  def delete(conn, params = %{"id" => id}) do
    case Defsol.delete_attachment(id) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Attachment deleted succesfully!")
        |> redirect(to: back_to(conn, params))

      {:error, _} ->
        conn
        |> put_flash(:error, "Failed to delete the attachment!")
        |> redirect(to: back_to(conn, params))
    end
  end
end

lib/hidria_web/controllers/defsol/cause_controller.ex
defmodule HidriaWeb.Defsol.CauseController do
  use HidriaWeb, :controller

  alias Hidria.Defsol

  def index(conn, params) do
    causes = Defsol.list_causes(params)
    search = get_in(params, ["search"])
    render(conn, "index.html", page: causes, search: search)
  end

  def show(conn, %{"id" => id}) do
    cause = Defsol.get_cause!(id)
    render(conn, "show.html", cause: cause)
  end

  def update(conn, %{"id" => id, "cause" => cause_params}) do
    cause = Defsol.get_cause!(id)
    attrs = merge_updated_by(conn, cause_params)

    case Defsol.update_cause(cause, attrs) do
      {:ok, _cause} ->
        conn
        |> put_flash(:info, "Cause updated successfully.")
        |> redirect(to: back_to(conn, cause_params))

      {:error, _} ->
        conn
        |> put_flash(:error, "Unable to update Cause")
        |> redirect(to: back_to(conn, cause_params))
    end
  end
end

lib/hidria_web/controllers/defsol/error_controller.ex
defmodule HidriaWeb.Defsol.ErrorController do
  use HidriaWeb, :controller

  alias Hidria.Defsol
  alias Hidria.Defsol.Error

  alias Hidria.Shopfloor

  def index(conn, params) do
    errors = Defsol.list_errors(params)
    search = get_in(params, ["search"])

    render(
      conn,
      "index.html",
      page: errors,
      search: search,
      parts: Shopfloor.list_parts(),
      stations: Shopfloor.list_stations()
    )
  end

  def new(conn, _params) do
    changeset = Defsol.change_error(%Error{active: true})
    render_new(conn, changeset)
  end

  def create(conn, %{"error" => error_params}) do
    params = merge_inserted_by(conn, error_params)

    case Defsol.create_error(params) do
      {:ok, error} ->
        conn
        |> put_flash(:info, "Error created successfully.")
        |> redirect(
          to:
            attachment_path(
              conn,
              :index,
              error_id: error.id,
              finish_path: home_path(conn, :index)
            )
        )

      {:error, %Ecto.Changeset{} = changeset} ->
        render_new(conn, changeset)
    end
  end

  defp render_new(conn, changeset) do
    render(
      conn,
      "new.html",
      changeset: changeset,
      parts: Shopfloor.list_parts(),
      stations: Shopfloor.list_stations()
    )
  end

  def edit(conn, %{"id" => id}) do
    error = Defsol.get_error!(id)
    changeset = Defsol.change_error(error)

    render(
      conn,
      "edit.html",
      error: error,
      changeset: changeset,
      parts: Shopfloor.list_parts(),
      stations: Shopfloor.list_stations()
    )
  end

  def update(conn, %{"id" => id, "error" => error_params}) do
    error = Defsol.get_error!(id)
    params = merge_updated_by(conn, error_params)

    case Defsol.update_error(error, params) do
      {:ok, _error} ->
        conn
        |> put_flash(:info, "Error updated successfully.")
        |> redirect(to: back_to(conn, error_params))

      {:error, _} ->
        conn
        |> put_flash(:error, "Unable to update error")
        |> redirect(to: back_to(conn, error_params))
    end
  end
end

lib/hidria_web/controllers/defsol/note_controller.ex
defmodule HidriaWeb.Defsol.NoteController do
  use HidriaWeb, :controller

  alias Hidria.Defsol
  alias Hidria.Defsol.Note

  alias HidriaWeb.Plugs.SelfControl
  plug(SelfControl, {Defsol, :get_note!} when action not in [:index, :new, :create])

  def index(conn, params) do
    notes =
      conn
      |> merge_inserted_by(params)
      |> Defsol.list_notes()

    search = get_in(params, ["search"])
    render(conn, "index.html", page: notes, search: search)
  end

  def new(conn, params) do
    changeset = Defsol.change_note(%Note{}, params)
    render(conn, "new.html", redirect_to(params) ++ [changeset: changeset])
  end

  def create(conn, all_params = %{"note" => note_params}) do
    params = merge_inserted_by(conn, note_params)

    case Defsol.create_note(params) do
      {:ok, _note} ->
        conn
        |> put_flash(:info, "Note created successfully.")
        |> redirect(to: back_to(conn, all_params))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    note = Defsol.get_note!(id)
    changeset = Defsol.change_note(note)
    render(conn, "edit.html", note: note, changeset: changeset)
  end

  def update(conn, %{"id" => id, "note" => note_params}) do
    note = Defsol.get_note!(id)
    params = merge_updated_by(conn, note_params)

    case Defsol.update_note(note, params) do
      {:ok, _note} ->
        conn
        |> put_flash(:info, "Note updated successfully.")
        |> redirect(to: defsol_note_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", note: note, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    note = Defsol.get_note!(id)
    {:ok, _note} = Defsol.delete_note(note)

    conn
    |> put_flash(:info, "Note deleted successfully.")
    |> redirect(to: defsol_note_path(conn, :index))
  end
end

lib/hidria_web/controllers/defsol/report_controller.ex
defmodule HidriaWeb.Defsol.ReportController do
  use HidriaWeb, :controller

  alias Hidria.Defsol
  alias Hidria.Defsol.Report

  alias HidriaWeb.Plugs.SelfControl
  plug(SelfControl, {Defsol, :get_report!} when action not in [:index, :new, :create])

  def index(conn, params) do
    reports =
      conn
      |> merge_inserted_by(params)
      |> Defsol.list_reports()

    search = get_in(params, ["search"])
    render(conn, "index.html", page: reports, search: search)
  end

  def new(conn, params = %{"solution_id" => solution_id}) do
    changeset = Defsol.change_report(%Report{}, params)
    solution = Defsol.get_solution!(solution_id)
    render(conn, "new.html", changeset: changeset, solution: solution)
  end

  def create(conn, %{"report" => report_params}) do
    params = merge_inserted_by(conn, report_params)

    case Defsol.create_report(params) do
      {:ok, report} ->
        Defsol.update_active(report)

        conn
        |> put_flash(:info, "Report created successfully.")
        |> redirect(to: home_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        case get_in(params, ["solution_id"]) do
          nil ->
            conn
            |> put_flash(:error, "Missing solution identifier!")
            |> redirect(to: admin_report_path(conn, :index))

          solution_id ->
            solution = Defsol.get_solution!(solution_id)
            render(conn, "new.html", changeset: changeset, solution: solution)
        end
    end
  end

  def edit(conn, %{"id" => id}) do
    report = Defsol.get_report!(id)
    changeset = Defsol.change_report(report)
    render(conn, "edit.html", report: report, changeset: changeset, solution: report.solution)
  end

  def update(conn, %{"id" => id, "report" => report_params}) do
    report = Defsol.get_report!(id)
    params = merge_updated_by(conn, report_params)

    case Defsol.update_report(report, params) do
      {:ok, _report} ->
        conn
        |> put_flash(:info, "Report updated successfully.")
        |> redirect(to: defsol_report_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", report: report, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    report = Defsol.get_report!(id)
    {:ok, _report} = Defsol.delete_report(report)

    conn
    |> put_flash(:info, "Report deleted successfully.")
    |> redirect(to: defsol_report_path(conn, :index))
  end
end

lib/hidria_web/controllers/defsol/solution_controller.ex
defmodule HidriaWeb.Defsol.SolutionController do
  use HidriaWeb, :controller

  alias Hidria.Defsol

  def index(conn, params) do
    solutions = Defsol.list_solutions(params)
    search = get_in(params, ["search"])
    render(conn, "index.html", page: solutions, search: search)
  end

  def show(conn, %{"id" => id}) do
    solution = Defsol.get_solution!(id)
    render(conn, "show.html", solution: solution)
  end
end

lib/hidria_web/views/admin/cause_view.ex
defmodule HidriaWeb.Admin.CauseView do
  use HidriaWeb, :view
end

lib/hidria_web/views/defsol/attachment_view.ex
defmodule HidriaWeb.Defsol.AttachmentView do
  use HidriaWeb, :view

  def render("index.json", %{attachments: attachments}) do
    %{data: render_many(attachments, __MODULE__, "attachment.json")}
  end

  def render("show.json", %{attachment: attachment}) do
    %{data: render_one(attachment, __MODULE__, "attachment.json")}
  end

  def render("attachment.json", %{attachment: attachment}) do
    %{
      id: attachment.id,
      error_id: attachment.error_id,
      fileinfo: attachment.fileinfo,
      inserted_at: attachment.inserted_at,
      updated_at: attachment.updated_at
    }
  end

  def render("errors.json", %{errors: e}) do
    errors = Enum.map(e, fn {error, points} -> %{type: error, datapoints: points} end)
    %{data: errors}
  end
end

lib/hidria_web/views/defsol/cause_view.ex
defmodule HidriaWeb.Defsol.CauseView do
  use HidriaWeb, :view
end

lib/hidria_web/views/defsol/error_view.ex
defmodule HidriaWeb.Defsol.ErrorView do
  use HidriaWeb, :view
end

lib/hidria_web/views/defsol/note_view.ex
defmodule HidriaWeb.Defsol.NoteView do
  use HidriaWeb, :view
  import HidriaWeb.NoteView.Helpers
end

lib/hidria_web/templates/defsol/cause/index.html.eex
<div class="card-2">
    <div class="card-header">
        <%= render_shared "title.html", title: "Listing Causes", search_path: defsol_cause_path(@conn, :index), conn: @conn, page: @page %>
    </div>
    <div class="card-body">

<%= for item <- @page do %>
    <div class="row py-2">
        <div class="col">
            <div class="card">
                <% color = if item.active, do: "danger", else: "primary" %>
                <div class="card-header bg-<%= color %> text-light">
                    <div class="d-flex flex-row">
                        <div><%= item.title %></div>
                        <div class="ml-auto">
                            <% back_to = Phoenix.Controller.current_path(@conn) %>
                            <%= if item.active do %>
                                <span data-toggle="tooltip" data-placement="top" title="Set as inactive">
                                    <% params = [cause: [active: false, redirect_to: back_to]] %>
                                    <%= link to: defsol_cause_path(@conn, :update, item, params), method: :put, class: "text-danger" do %>
                                        <i class="fa fa-toggle-on text-light"></i>
                                    <% end %>
                                </span>
                            <% else %>
                                <span data-toggle="tooltip" data-placement="top" title="Set as active">
                                    <% params = [cause: [active: true, redirect_to: back_to]] %>
                                    <%= link to: defsol_cause_path(@conn, :update, item, params), method: :put, class: "text-primary" do %>
                                        <i class="fa fa-toggle-off text-light"></i>
                                    <% end %>
                                </span>
                            <% end %>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title">Description</h5>
                    <p class="card-text"><%= item.description %></p>
                    <h5 class="card-title">Detection</h5>
                    <p class="card-text"><%= item.detection %></p>

                    <%= render_shared "authorable.html", item: item %>

                    <%= for attachment <- item.attachments do %>
                        <a href="<%= Hidria.AttachmentUpload.url({attachment.fileinfo, attachment}, :original) %>" class="lightbox" data-lightbox-gallery="error_gallery_<%= item.id %>" title="">
                            <img src="<%= Hidria.AttachmentUpload.url({attachment.fileinfo, attachment}, :thumb) %>" alt="">
                        </a>
                    <% end %>
                    <div class="py-2">
                        <%= link "Solutions", to: defsol_solution_path(@conn, :index, cause_id: item.id), class: "btn btn-primary btn-xs" %>
                    </div>
                </div>

                <div class="card-footer bg-transparent">
                    <div class="d-flex flex-row justify-content-end">
                        <div class="align-self-center"> Something wrong with this cause? </div>
                        <div class="px-2">
                            <%= link "Note", to: defsol_note_path(@conn, :new, cause_id: item.id), class: "btn btn-sm btn-success" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

<div class="pt-3">
    <%= render_shared "pagination.html", conn: @conn, page: @page, path_opts: [path: &defsol_cause_path/3, action: :index] %>
</div>
    </div>
</div>

lib/hidria_web/templates/defsol/cause/show.html.eex
<h2>Show Cause</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @cause.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @cause.description %>
  </li>

  <li>
    <strong>Detection:</strong>
    <%= @cause.detection %>
  </li>

  <li>
    <strong>Active:</strong>
    <%= @cause.active %>
  </li>

</ul>

<span><%= link "Edit", to: admin_cause_path(@conn, :edit, @cause) %></span>
<span><%= link "Back", to: admin_cause_path(@conn, :index) %></span>