lib/hidria_web/router.ex
defmodule HidriaWeb.Router do
  use HidriaWeb, :router

  alias HidriaWeb.Plugs.AssignSession
  alias HidriaWeb.Plugs.AuthUser
  alias HidriaWeb.Plugs.AuthEnsure
  alias HidriaWeb.Plugs.AuthRole
  alias HidriaWeb.Plugs.CheckState

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(AssignSession, [:current_station, :current_part])
    plug(AuthUser)
  end

  pipeline :authorize do
    plug(AuthEnsure)
  end

  pipeline :state do
    plug(CheckState, :station)
    plug(CheckState, :part)
  end

  pipeline :operator do
    plug(AuthEnsure)
    plug(AuthRole, :operator)
  end

  pipeline :lead do
    plug(AuthEnsure)
    plug(AuthRole, :lead)
  end

  pipeline :admin do
    plug(AuthEnsure)
    plug(AuthRole, :admin)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", HidriaWeb do
    pipe_through(:browser)
    get("/login", LoginController, :new)
    post("/login", LoginController, :create)
  end

  scope "/", HidriaWeb do
    pipe_through([:browser, :operator])
    resources("/state", StateController, only: [:show, :create, :delete], param: "resource")
    get("/logout", LoginController, :delete)

    resources("/user", UserController, only: [:show, :edit, :update])
    get("/users/:id/newpassword", UserController, :new_password)
    put("/users/:id/updatepassword", UserController, :update_password)

    get("/attachments", Defsol.AttachmentController, :index)
    delete("/attachments/:id", Defsol.AttachmentController, :delete)
  end

  scope "/", HidriaWeb do
    pipe_through([:browser, :operator, :state])

    get("/", HomeController, :index)
  end

  scope "/", HidriaWeb.Shopfloor, as: :shopfloor do
  end

  scope "/", HidriaWeb.Defsol, as: :defsol do
    pipe_through([:browser, :operator, :state])
    resources("/errors", ErrorController, except: [:show, :delete])
    resources("/causes", CauseController, only: [:index, :show, :update])
    resources("/solutions", SolutionController, only: [:index, :show])
    resources("/reports", ReportController, except: [:show])
    resources("/notes", NoteController, except: [:show])
  end

  scope "/admin", HidriaWeb.Admin, as: :admin do
    pipe_through([:browser, :lead])

    resources("/parts", PartController, except: [:show])
    resources("/errors", ErrorController, except: [:show])
    post("/errors/:id/clone", ErrorController, :clone)
    resources("/causes", CauseController, except: [:show])
    resources("/solutions", SolutionController, except: [:show])
    resources("/reports", ReportController)
    resources("/notes", NoteController)
  end

  scope "/admin", HidriaWeb.Admin, as: :admin do
    pipe_through([:browser, :admin])

    resources("/users", UserController)
    resources("/stations", StationController, except: [:show])
    get("/users/:id/newpassword", UserController, :new_password)
    put("/users/:id/updatepassword", UserController, :update_password)
  end

  # Other scopes may use custom stacks.
  scope "/api", HidriaWeb do
    pipe_through(:api)
    post("/attachments", Defsol.AttachmentController, :create)
  end
end

lib/hidria_web/controllers/home_controller.ex
defmodule HidriaWeb.HomeController do
  use HidriaWeb, :controller

  alias Hidria.Defsol

  def index(conn, params) do
    params =
      params
      |> station_params(conn)
      |> part_params(conn)

    active_errors = Defsol.list_active_errors(params)
    reports = Defsol.list_reports_by_shopfloor(params)
    render(conn, "index.html", active_errors: active_errors, reports: reports)
  end

  def station_params(params, %{assigns: %{current_station: station}}) do
    %{station_id: station.id} |> Enum.into(params)
  end

  def station_params(params, _conn), do: params

  def part_params(params, %{assigns: %{current_part: part}}) do
    %{part_id: part.id} |> Enum.into(params)
  end

  def part_params(params, _conn), do: params
end

lib/hidria_web/views/home_view.ex
defmodule HidriaWeb.HomeView do
  use HidriaWeb, :view
end

lib/hidria_web/templates/home/index.html.eex
<% len = @active_errors |> Enum.to_list() |> length() %>
<%= if len > 0 do %>
    <%= render HidriaWeb.Defsol.ErrorView, "list.html", conn: @conn, errors: @active_errors %>
    <%= render_shared "pagination.html", conn: @conn, page: @active_errors, path_opts: [path: &home_path/3, action: :index] %>
<% else %>
    <div class="row">
        <div class="col">
            <div class="card-2 text-center">
                <div class="card-body">
                    <h5 class="card-title">No Active Errors!</h5>
                    <p class="card-text">If you have a problem in production you can look through possible errors, try to solve them or notify others of its presence.</p>
                    <a class="btn btn-primary" href="<%= defsol_error_path(@conn, :index, station_part_params(@conn)) %>" role="button">All Errors</a>
                </div>
            </div>
        </div>
    </div>
<% end %>

<div class="row pt-3">
    <div class="col">
        <div class="card-2 text-center">
            <div class="card-body">
                <h5 class="card-title">Can't find the error?</h5>

                <p class="card-text">If you have found a new error that is not already described, please create a new one!</p>
                <a class="btn btn-success" href="<%= defsol_error_path(@conn, :new, station_part_params(@conn)) %>" role="button">New Error</a>
                <p class="card-text">If there is something in general not working please create a note!</p>
                <a class="btn btn-success" href="<%= defsol_note_path(@conn, :new) %>" role="button">New Note</a>
            </div>
        </div>
    </div>
</div>

<div class="row pt-3">
    <div class="col">
        <div class="card-2 text-center">
            <div class="card-body">
                <h5 class="card-title">Latest reports!</h5>
                <%= for item <- @reports do %>
            <div class="d-flex flex-row">
                <div>
                    <img class="img-user-small" src="<%= Avatar.url({item.author.avatar, item.author}, :thumb) %>" alt="User">
                </div>
                <div class="col">
                    <div class="card text-left">
                        <% color = if item.success, do: "primary", else: "danger" %>
                        <div class="card-header bg-<%= color %> text-light">
                            <div class="d-flex flex-row">
                                <div class="small"><%= inserted_at(item) %></div>
                                <div class="small px-1">
                                    <%= item.author.fullname %>
                                    <%= if item.success do %>
                                        applied <%= item.solution.title %>
                                    <% else %>
                                        failed to apply <%= item.solution.title %>
                                    <% end %>
                                </div>
                            </div>
                            <p class="card-text"><%= item.description %></p>
                        </div>
                    </div>
                </div>
            </div>
                <% end %>
            </div>
        </div>
    </div>
</div>